---

- name: merge syslog_sources configuration between defaults and custom
  set_fact:
    syslog_sources: "{{ syslog_sources_default |
      combine( syslog_sources, recursive=True ) }}"

- name: merge syslog_logs configuration between defaults and custom
  set_fact:
    syslog_logs: "{{ syslog_logs_default + syslog_logs | flatten | unique }}"

- name: detect config version
  shell: |
    syslog-ng --version | grep "Config version" | awk -F ': ' '{print $2}'
  register: _syslog_config_version
  tags:
    - syslog-ng
    - configuration

- name: set syslog config version
  set_fact:
    syslog_config_version: '{{ _syslog_config_version.stdout }}'
  when:
    - _syslog_config_version is defined
    - _syslog_config_version.stdout is defined
  tags:
    - syslog-ng
    - configuration

- name: write splittet configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/syslog-ng/conf.d/{{ item }}"
  notify: restart syslog-ng
  loop:
    - sources.conf
    - destinations.conf
    - filters.conf
    - logs.conf
  tags:
    - syslog-ng
    - configuration

- name: configure syslog-ng.conf
  template:
    src: syslog-ng.conf.j2
    dest: /etc/syslog-ng/syslog-ng.conf
  notify: restart syslog-ng
  tags:
    - syslog-ng
    - configuration
