---

- include_tasks: 01-install.yml
- include_tasks: 05-configure.yml
- include_tasks: 06-configure_journald.yml
  when: ( ansible_service_mgr is defined and ansible_service_mgr | lower == "systemd" )
- include_tasks: 10-service.yml
